// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rulvdsqwhdilwicbnoni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bHZkc3F3aGRpbHdpY2Jub25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTgwMjYsImV4cCI6MjA3MDY3NDAyNn0.mB3bne8ZAppksDp--zCRMWrW05A0Wbg7J8YRBekPvmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});